language: python
python:
    - 2.7

install: 
    - sudo apt-get install libxml2-dev libxslt-dev python-dev
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install coveralls

script: 
    - py.test --verbose --cov-config .coveragerc --cov sqlScriptBuilder --cov-report xml

after_success:
    - coveralls